name: Date Time Variable
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  Data-Time-Variable:
    runs-on: ubuntu-latest
    env:
      GITDATE: 0-day
    steps:
      - run: echo "ðŸŽðŸ Date Time Variable"
      - run: echo "$(date)" > $GITDATE
      - run: echo "GITDATE $GITDATE"
      
        
            
      
